// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASavcTY5CWmSQNvSdLo7JtMehgPgRsgA4',
    appId: '1:651034106279:web:baaf5b52d8e515659dfe82',
    messagingSenderId: '651034106279',
    projectId: 'activetracker-b0a69',
    authDomain: 'activetracker-b0a69.firebaseapp.com',
    storageBucket: 'activetracker-b0a69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzQsRMxYhOCt0Ps-A950tEdNE_7stvolA',
    appId: '1:651034106279:android:1cb146be6d3f2ab89dfe82',
    messagingSenderId: '651034106279',
    projectId: 'activetracker-b0a69',
    storageBucket: 'activetracker-b0a69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf0WbSLjp_3a2IqvfrawX-Fne7S73GbRs',
    appId: '1:651034106279:ios:e60f33e90f39e2589dfe82',
    messagingSenderId: '651034106279',
    projectId: 'activetracker-b0a69',
    storageBucket: 'activetracker-b0a69.appspot.com',
    iosBundleId: 'com.example.activetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf0WbSLjp_3a2IqvfrawX-Fne7S73GbRs',
    appId: '1:651034106279:ios:e60f33e90f39e2589dfe82',
    messagingSenderId: '651034106279',
    projectId: 'activetracker-b0a69',
    storageBucket: 'activetracker-b0a69.appspot.com',
    iosBundleId: 'com.example.activetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASavcTY5CWmSQNvSdLo7JtMehgPgRsgA4',
    appId: '1:651034106279:web:149fce2cac73c7c79dfe82',
    messagingSenderId: '651034106279',
    projectId: 'activetracker-b0a69',
    authDomain: 'activetracker-b0a69.firebaseapp.com',
    storageBucket: 'activetracker-b0a69.appspot.com',
  );
}
